version: '3.4'

services:
 finder:
    hostname: finder
    image: finder
    container_name: finder    
    build:
      dockerfile: github-finder-client/prod.Dockerfile
    ports:
       - "3000:80"
    env_file:
      - Variables/.env